model:
  _target_: geobench_exp.torch_toolbox.model.GeoBenchClassifier
  model: "resnet18"
  weights: ResNet18_Weights.SENTINEL2_RGB_MOCO
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-4

datamodule:
  batch_size: 128