experiment:
  generate_experiment_dir: /mnt/SSD2/nils/geo_bench_stuff/experiments
  # TODO experimnet name and partition name are redundant
  # same with benchmark name and benchmark dir
  experiment_name: 0.01x_train # prefix
  benchmark_dir: /mnt/SSD2/nils/geo_bench_stuff/classification_v1.0
  benchmark_name: classification_v0.9.1
  partition_name: 0.01x_train
  # tasks: # ["so2sat", "brick_kiln_v1.0", "eurosat", "bigearthnet", "pv4ger_classification", "forestnet_v1.0"]
  num_seeds: 1

datamodule:
  _target_: geobench_exp.torch_toolbox.dataset.DataModule
  num_workers: 4
  batch_size: 256
  band_names: "all" #["red", "green", "blue"]
  format: hdf5

trainer: # all flags for pytorch lightning Trainer module, see https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
  _target_: lightning.Trainer
  devices: [0]
  accelerator: gpu
  max_epochs: 600
  max_steps: -1
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  val_check_interval: 0.25
  log_every_n_steps: 10
  enable_progress_bar: True