experiment:
  generate_experiment_dir: /mnt/data/experiments/nils/camera_class_beyond_seeds
  experiment_name: 1.00x_train # prefix
  experiment_type: seeded_runs
  partition_name: 1.00x_train
  benchmark_name: classification_v0.8.5
  benchmark_dir: /mnt/data/cc_benchmark/classification_v0.8.5
  best_hparam_config: /mnt/home/geo-bench-experiments/geobench_exp/configs/class_beyond_hparams_camera.json
  num_seeds: 12
  tasks: ["m-bigearthnet", "m-brick-kiln", "m-eurosat", "m-so2sat"]
model:
  model_generator_module_name: geobench_exp.torch_toolbox.model_generators.timm_generator
  pretrained: True
  backbone: resnet50 # resnet18, convnext_base, vit_tiny_patch16_224, vit_small_patch16_224. swinv2_tiny_window16_256
  model_name: resnet50_DINO
dataset:
  band_names: all
wandb:
  project: geobench_exp # wandb project name
  entity: climate-benchmark # user or team entity that hosts a project
  mode: offline