experiment:
  generate_experiment_dir: /mnt/data/experiments/nils/camera_segmentation_seeds
  experiment_name: 1.00x_train # prefix
  experiment_type: seeded_runs # standard, seeded_runs, sweew
  partition_name: 1.00x_train
  benchmark_dir: /mnt/data/cc_benchmark/segmentation_v0.4
  benchmark_name: segmentation_v0.4
  best_hparam_config: /mnt/home/geo-bench-experiments/geobench_exp/configs/seg_hparams_camera.json
  num_seeds: 10
  tasks: ["m-chesapeake", "m-SA-crop-type", "m-NeonTree",  "m-pv4ger-seg"] # "m-cashew-plant" "m-nz-cattle"
  # tasks: ["m-nz-cattle"]
model:
  model_generator_module_name: geobench_exp.torch_toolbox.model_generators.py_segmentation_generator
  encoder_type: resnet101 # resnet18,
  pretrained: True
  decoder_type: DeepLabV3 # DeepLabV3, Unet
  model_name: resnet101_DeepLabV3
  desired_input_size: 224
dataset:
  band_names: ["red", "green", "blue"] #al
wandb:
  project: geobench_exp # wandb project name
  entity: climate-benchmark # user or team entity that hosts a project
  mode: offline