experiment:
  generate_experiment_dir: /mnt/data/experiments/nils/camera_class_seeds
  experiment_name: 0.10x_train # prefix
  experiment_type: seeded_runs
  partition_name: 0.10x_train
  benchmark_dir: /mnt/data/cc_benchmark/classification_v0.8.5
  benchmark_name: classification_v0.8.5
  best_hparam_config: /mnt/home/geo-bench-experiments/geobench_exp/configs/class_hparams_camera.json
  num_seeds: 4
model:
  model_generator_module_name: geobench_exp.torch_toolbox.model_generators.timm_generator
  pretrained: True
  backbone: vit_small_patch16_224 ## resnet18, convnext_base, vit_tiny_patch16_224, vit_small_patch16_224. swinv2_tiny_window16_256
  model_name: vit_small_patch16_224
dataset:
  band_names: ["red", "green", "blue"] #all