experiment:
  generate_experiment_dir: /mnt/SSD2/nils/geo_bench_stuff/experiments
  experiment_name: 0.05x_train # prefix
  benchmark_dir: /mnt/SSD2/nils/geo_bench_stuff/segmentation_v1.0
  partition_name: 0.05x_train
  benchmark_name: segmentation_v1.0
  num_seeds: 1

datamodule:
  _target_: geobench_exp.torch_toolbox.dataset.DataModule
  num_workers: 4
  batch_size: 16
  band_names: ["red", "green", "blue"]
  format: hdf5

trainer: # all flags for pytorch lightning Trainer module, see https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
  _target_: lightning.Trainer
  devices: [0]
  accelerator: gpu
  max_epochs: 600
  max_steps: -1
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  val_check_interval: 0.25
  deterministic: False
  log_every_n_steps: 10
  enable_progress_bar: true
  precision: 16